### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by rolandh** [vloschiavo/powerwall2#13]
Are you aware of any way to limit the charge/discharge rate of the powerwall 2?

I have realtime rates (30 min update interval) and also access to 12 hour look ahead. So I wish to limit the charging (if the buyback rate is high) and limit the discharging (if the buyback rate is low).

I can see that I can basically just use an on/off controller here by literally shutting the powerwall off entirely. But it would be nicer to rate limit it.

Are you aware of any method to do this?

**Comment by vloschiavo** [comment]
I don't think this is possible with the local API
