### ISSUE TITLE
Charge and Discharge commands via API?

### ISSUE THREAD

**Issue by e123149** [vloschiavo/powerwall2#14]
Has anyone been able to manually charge and discharge via the API or Modbus?

**Comment by BJReplay** [comment]
Charge via API - yes, just set the mode to backup, and it will charge
(@3.3kW) up to (almost, in the latest firmware - about 99.5%) to 100%.

Discharge via API - no, other than setting the mode to self consumption,
where it will discharge to meet site load not being met by solar.

It doesn't appear possible to make it discharge into the grid.
