### ISSUE TITLE
Installer Password Reset

### ISSUE THREAD

**Issue by rstad944** [vloschiavo/powerwall2#23]
As part of a service request I made to Tesla (frequency based solar power reduction), evidently the engineer working on my system performed a reset on my system's Installer password.  This became obvious when my script that switches SELF/BKUP mode failed to authenticate:
{"code":401,"error":"bad credentials","message":"Login Error"}

The short term solution was to click on the local LAN webpage FORGOT PASSWORD and then on the next menu, RESET.  This resulted in a 10 character random caps A-Z password.  I updated my script to replace the S+serial-number with the new password.  All works as before.

Given that Tesla could update the password at any time, the long term solution would be to have the script react to the 401 "bad credentials" by using the API /password/reset to obtain a new password.  Unfortunately I do not understand the app.xxxx.js code well enough to formulate the POST request.  It needs the unit S+serial-number and returns the new password, but how to format?

**Comment by vloschiavo** [comment]
See the bash example here: https://github.com/vloschiavo/powerwall2/blob/master/samples/powerwallstats.sh

You can use the userid: customer and a password of your choosing to accomplish logins as of version 20.49.0
