### ISSUE TITLE
MeterTypes limited to 4 meters

### ISSUE THREAD

**Issue by jrester** [vloschiavo/powerwall2#30]
It seems that their are only 4 meter types in version 1.45.2 available:
* solar
* load
* site
* battery
Therefore `/api/meters/aggregates` only returns data about those 4. This comes from reverse engineering the source code so I'm not sure if this is correct. Does anybody have other responses?

**Comment by vloschiavo** [comment]
Yes, that's what I'm seeing now on 1.45.2 as well.
