### ISSUE TITLE
Nominal system energy with 2 powerwalls

### ISSUE THREAD

**Issue by kennellink** [vloschiavo/powerwall2#32]
I have two powerwalls, but site_info returns nominal_system_energy_kWh of 13.5
I would have thought it should show 27 since there are two batteries.
I'm seeing signs that my system is misconfigured or something since it only charges/discharges ~13kWh each day.
Not a comment on your great work.  Just wondering what your thoughts were on this.  Am I wrong?
Thanks!
Brad Schuler

**Comment by StephenNorris** [comment]
I have the same results, with two power walls. Oddly, nominal_system_power_kW is correct at 10.
