### ISSUE TITLE
Has anyone managed to get the PW2 to force discharge on command?

### ISSUE THREAD

**Issue by rolandh** [vloschiavo/powerwall2#33]
Is there anyway to force the PW2 to discharge on command regardless of household draw/usage?

This is a requirement for being able to rate surf. I get billed in 30 min intervals with peaks/troughs through out the day. Our electricity price can go negative at times and very high at others, being able to control charge/discharge would be amazing.

**Comment by spoonwzd** [comment]
You can do this just by setting the reserve amount to different values - if the reserve % is set higher than the current stored amount the Powerwall will pull from the grid to charge to the defined % level. If the reserve % is set lower than the current stored amount the Powerwall will discharge.

**Comment by daveoxley** [comment]
Setting the reserve amount will allow the discharge to match the current household demand. Is there anyway to force the powerwall to discharge to the grid?

**Comment by vloschiavo** [comment]
I don't think this is possible.
