### ISSUE TITLE
Add table of endpoints + relative links

### ISSUE THREAD

**Issue by vls29** [vloschiavo/powerwall2#38]
Hi @vloschiavo ,

I was looking at the documentation you've got the other night to see if there were any endpoints I could document and wondered if you'd be up for a bit of a re-structure of the readme to have a table of endpoints + links to the relevant detail behind them?

I've got an example in a branch here: https://github.com/vls29/powerwall2/tree/structure-readme#api-reference

I wanted to run it past you and find out your thoughts before I went ahead and re-structured everything only to find you weren't interested in the change :)

If you do think it's worth continuing with, I can work on it over the next few weeks and send you a pull request when the majority has been tabulated.

Regards
vls29

**Comment by vloschiavo** [comment]
Yes!  I like!  Happy to merge when you're done.
