### ISSUE TITLE
Tesla app history reset

### ISSUE THREAD

**Issue by fdawg4l** [vloschiavo/powerwall2#47]
Hi

Nice work!  I used what you did here and built this (https://github.com/fdawg4l/tesla-gateway-getter).  I've had it running for about a month and have noticed that the history in the iOS Tesla App gets zeroed out.   I go to powerflow, then hit the energy usage bars in the upper right, and the `week`, `month`, and `year`, entries are 0.  In fact, through out the day, the day totals go to zero while the graphs look fine (as in they have non zero data).

I was wondering if you encountered this.  Is my service poking the TEG api reseting the history?

Which brings up more questions-  how does the app even get history?  Looking through the API you've documented, I don't see anything with historical numbers.  Are they (Tesla) recording these details offsite and reporting it to the app with their own service?

Anyway, thank you for documenting everything.  It's been super helpful.

**Comment by vloschiavo** [comment]
Thanks!  It's been a team effort!

You dashboard looks great!  Thanks for sharing.

Re: History.  Yes, the Tesla is collecting data from your powerwall and storing telemetry data on their servers in their data centers.  The mobile app is reading history from Tesla via their API (not the powerwall's direct api).

I don't believe that there is any correlation between you collecting data from the local powerwall causing the Telsa Mobile App data sources to got to zero.    

Glad it's been useful!

-V
