### ISSUE TITLE
Problems receiving data with an ESP8266 on new Powerwall version

### ISSUE THREAD

**Issue by MoritzLerch** [vloschiavo/powerwall2#54]
Hey, 

probably I'll find someone here for this issue... So I got this project running to display data on an LCD screen with an ESP8266 attached. It's open source, I launched it about two days ago. https://github.com/MoritzLerch/pv_display

Problem is that I'm just not able to connect to the Powerwall anymore with the ESP8266. If I do it with curl on my PC everything is fine. What I'm thinking is that there was a Powerwall API update about two days ago. I also found some new information in some endpoints. So this will probably be the cause for my project to not work anymore. I already asked some people but unfortunately we didn't find a solution yet. 

Version would be `21.20.6`...

Is someone here who has deeper information what the API update did update? Or someone who's experiencing similar problems on the ESP8266 platform?

**Comment by BJReplay** [comment]
Sorry, no idea what the update changed.

A lot of the "it works on curl, just not on platform X" problems come down
to different default options for things like TLS version, accepting various
encodings, headers and cookies, trusting the self signed cert,
etc.

Double checking defaults or wireshark to look at the difference will
probably allow you to spot the difference - at least until someone else is
bumped to the same version.

**Comment by BJReplay** [comment]
Further to my last:

Firstly, I'm updated to 21.20.6 as well, and everything is just working as
expected.

I had a look at your source code, and the only thing to spot that might be
worth looking at would be HTTP/1.0 on the SOC and Power requests.  I saw
the comment re chunked transfer encoding - maybe that's the change?  I note
you use 1.1 for the login sequence. Perhaps an accept header would work
around that?

I'm sorry, I don't know enough about how httpsClient works to offer
anything more helpful.

I am using .Net HttpWebRequest and the only thing I'm doing is adding the
auth cookie for my SOC and Power calls.

Obviously HttpWebRequest != httpsClient, but I know I didn't need to
specify HTTP/1.0

Hope this helps a bit.

**Comment by MoritzLerch** [comment]
Hey, thanks for your help. I don't think that those HTTP versions would change anything. The problem occurs before we even get to the http-request point. So I'm actually not even able to connect via HTTPS to the powerwall. So when I was debugging, I found this error `BSSL:_wait_for_handshake: failed` when I'm trying to connect to the host. So something will be around with that handshake. [The while loop](https://github.com/MoritzLerch/pv_display/blob/db5a520d18739716266433ea8cda33937ffd9b02/lib/Powerwall/Powerwall.h#L59-L63) just keeps running until the retry counter hits the "stopping" value. Problem would be this probably: `httpsClient.connect(powerwall_ip, 443)`

That thing that I have to enable HTTP/1.0 is because the meters_aggregates (or something) endpoint returns a lot of data and that involves these chunks I was not able to handle... But that also might or will be an issue I only have to deal with because I'm on an ESP8266.
