### ISSUE TITLE
[Exchange] NodeRed Setup

### ISSUE THREAD

**Issue by MoritzLerch** [vloschiavo/powerwall2#58]
Hey, 

I'm new to NodeRed and wanted to ask you guys how you have set up your Flows in NodeRed regarding the Powerwall. It would be fantastic if you could share your configurations!

Best regards, 
Moritz

(@vloschiavo maybe you could enable the discussions tab for future conversations so it doesn't have to be done through the issues)

**Comment by vloschiavo** [comment]
Great idea!  Done!
