### ISSUE TITLE
Reset via API

### ISSUE THREAD

**Issue by cburne-oshyn** [vloschiavo/powerwall2#74]
I'm having an issue w/ my powerwall that it stops discharging during the evening.  It goes from 100% to 70-80% and then goes into standby.  The only way i've found to kick it into discharging again is to do a reset on the gateway.

I'm looking for a way to do that via the API and I am not finding one that works via the APIs that have been documented so far.  The most promising one is /solar_powerwall/reset, but it requires a POST with a JSON payload and I'm not sure what it takes.

When sending no valid payload, i get:
{
    "code": 400,
    "error": "unexpected end of JSON input",
    "message": "Unable to unmarshal body"
}

I dont' want ot keep going out there every night and resetting manually so wondering if anyone has found a way to do the same type of "reset" that you do on the gateway via the api (or any other automated mechanism.

Thanks

**Comment by GBDownUnder** [comment]
hmm, have you tried contacting Tesla support about the issue?
powerwallsupportna@tesla.com
