### ISSUE TITLE
can't set ToU via API

### ISSUE THREAD

**Issue by icepicknz** [vloschiavo/powerwall2#8]
running 1.18.0
While i can set ToU setting in the app; can't do via the API

curl --header "Authorization: BearerTOKEN==" -X POST -d '{"mode":"autonomous","backup_reserve_percent":5}' http://192.168.33.5/api/operation
{"code":500,"error":"Mode must be either self_consumption or backup","message":"Unable to set operational mode"}Barrys-MacBook-Pro:~ barrymurphy$

**Comment by vloschiavo** [comment]
@icepicknz - The current version of the Powerwall software has been updated to 1.45.2.  
Can you check the examples in issue #18 (https://github.com/vloschiavo/powerwall2/issues/18) and let me know if that works for you?  If yes, I'd appreciate a pull request.
